
import streamlit as st

st.set_page_config(page_title="Capital Budgeting", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
This lab explores capital budgeting concepts and techniques. Navigate through the pages to learn more.
""")

page = st.sidebar.selectbox(label="Navigation", options=["Budget vs Actual", "NPV Calculation", "Payback Period"])

if page == "Budget vs Actual":
    from application_pages.budget_actual import run_budget_actual
    run_budget_actual()
elif page == "NPV Calculation":
    from application_pages.npv_calculation import run_npv_calculation
    run_npv_calculation()
elif page == "Payback Period":
    from application_pages.payback_period import run_payback_period
    run_payback_period()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
