
import streamlit as st

st.set_page_config(page_title="Capital Budgeting", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("Capital Budgeting")
st.divider()

st.markdown("""
In this lab, we will explore the fundamental concepts of capital budgeting, a crucial aspect of financial management. Capital budgeting involves the process of evaluating potential investment projects to determine which ones are worth pursuing. It helps organizations make informed decisions about allocating resources to projects that will generate the highest returns and contribute to the company's long-term profitability.

We will cover several key techniques used in capital budgeting, including:

*   **Net Present Value (NPV):**  NPV is a method used to determine the current value of all future cash flows generated by a project, discounted by a required rate of return.
    $$
    NPV = \sum_{t=1}^{n} \frac{CF_t}{(1 + r)^t} - Initial Investment
    $$
    Where:
    *   $CF_t$ = Cash flow in period t
    *   $r$ = Discount rate
    *   $n$ = Number of periods

*   **Internal Rate of Return (IRR):** IRR is the discount rate that makes the net present value (NPV) of all cash flows from a particular project equal to zero.
    $$
    0 = \sum_{t=1}^{n} \frac{CF_t}{(1 + IRR)^t} - Initial Investment
    $$
    Where:
    *   $CF_t$ = Cash flow in period t
    *   $IRR$ = Internal Rate of Return
    *   $n$ = Number of periods

*   **Payback Period:** The payback period is the amount of time it takes for a project to recover its initial investment.

*   **Discounted Payback Period:** Similar to the payback period, but it considers the time value of money by discounting future cash flows.

This lab will provide you with the tools and knowledge to analyze investment opportunities and make sound capital budgeting decisions.
""")

# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Budgeting", "Variance Analysis", "Trend Analysis"])

if page == "Budgeting":
    from application_pages.budgeting import run_budgeting
    run_budgeting()
elif page == "Variance Analysis":
    from application_pages.variance_analysis import run_variance_analysis
    run_variance_analysis()
elif page == "Trend Analysis":
    from application_pages.trend_analysis import run_trend_analysis
    run_trend_analysis()
# Your code ends

st.divider()
st.write("© 2025 QuantUniversity. All Rights Reserved.")
st.caption("The purpose of this demonstration is solely for educational use and illustration. "
           "Any reproduction of this demonstration "
           "requires prior written consent from QuantUniversity. "
           "This lab was generated using the QuCreate platform. QuCreate relies on AI models for generating code, which may contain inaccuracies or errors")
